##############################################################################
# YAML Anchors
##############################################################################
infrastructure_vars: &infrastructure_vars
  TF_VAR_k8s_min_master_version: ((k8s_min_master_version))
  TF_VAR_gcp_folder_id: ((google.folder_id))
  TF_VAR_gcp_billing_account: ((google.billing_account))
  TF_VAR_project_env: ((google.project_label))
  TF_VAR_machine_type: ((google.machine_type))
  TF_VAR_project_name: ((google.project_name))

run_stress_test_vars: &run_stress_test_vars
  PROJECT_NAME: ((google.project_name))
  REGION: ((google.region))
  REQUESTS_JSON: ((requests_json))
  LOCUST_OPTIONS: '--no-web --clients ((number_of_clients_per_pod)) --hatch-rate ((hatch_rate)) --run-time ((run_time)) --csv=output -L WARNING'
  RUNNER_FULLY_QUALIFIED_DOMAIN_NAME: ((runner_fully_qualified_domain_name))
  DOCKER_REGISTRY: ((docker.app_registry))
  USER_WAIT_TIME_MIN_SECONDS: ((user_wait_time_min_seconds))
  USER_WAIT_TIME_MAX_SECONDS: ((user_wait_time_max_seconds))
  REQUESTED_CPU_PER_POD: ((requested_cpu_per_pod))
  REQUESTED_MEMORY_PER_POD: ((requested_memory_per_pod))
  PARALLELISM: ((parallelism))
  TIMEOUT: ((timeout))

##############################################################################
# Resources
##############################################################################

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:

##############################################################################
# Git Repositories
##############################################################################

  - name: eq-survey-runner-benchmark
    type: git
    source:
      uri: https://github.com/ONSdigital/eq-survey-runner-benchmark.git
      branch: stress-test

  - name: eq-terraform-load-generator
    type: git
    source:
      uri: https://github.com/ONSdigital/eq-terraform-load-generator.git
      branch: stress-test

##############################################################################
# Docker Images
##############################################################################

  - name: eq-survey-runner-benchmark-image
    type: docker-image
    source:
      repository: ((docker.app_registry))/eq-survey-runner-benchmark
      username: _json_key
      password: ((gcp.service_account_json))

  - name: eq-infrastructure-build-image
    type: docker-image
    source:
      repository: ((docker.build_image_registry))/eq-infrastructure-build-image

##############################################################################
# Misc Resources
##############################################################################

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack.webhook))

jobs:

##############################################################################
# Build Survey Runner Benchmark
##############################################################################

  - name: build-survey-runner-benchmark
    plan:
    - get: eq-survey-runner-benchmark
    - put: eq-survey-runner-benchmark-image
      params:
        build: eq-survey-runner-benchmark
        tag_file: eq-survey-runner-benchmark/.git/HEAD
        tag_as_latest: true
      get_params:
        skip_download: true
    on_failure:
      put: slack-alert
      params:
        channel: '#((slack_channel_name))'
        attachments:
          - pretext: Benchmark Image Build Failed
            color: danger
            title: Concourse Build $BUILD_ID
            title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID

##############################################################################
# Deploy Infrastructure
##############################################################################

  - name: deploy-infrastructure
    serial_groups: [run-stress-test]
    plan:
    - get: eq-terraform-load-generator
    - get: eq-infrastructure-build-image
    - get: eq-survey-runner-benchmark
    - task: Build & Deploy Infrastructure
      file: 'eq-terraform-load-generator/ci/deploy-infrastructure.yaml'
      image: eq-infrastructure-build-image
      params:
        <<: *infrastructure_vars
    on_failure:
      put: slack-alert
      params:
        channel: '#((slack_channel_name))'
        attachments:
          - pretext: Load Generator Infrastructure Deploy Failed
            color: danger
            title: Concourse Build $BUILD_ID
            title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID
    on_success:
      put: slack-alert
      params:
        channel: '#((slack_channel_name))'
        attachments:
          - pretext: Load Generator Infrastructure Deploy Passed
            color: good
            title: Concourse Build $BUILD_ID
            title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID

##############################################################################
# Run Stress Test
##############################################################################

  - name: run-stress-test
    serial_groups: [run-stress-test]
    plan:
    - get: eq-survey-runner-benchmark
      passed:
        - deploy-infrastructure
        -  build-survey-runner-benchmark
      trigger: true
    - task: Run Survey Runner Stress Test
      file: 'eq-survey-runner-benchmark/ci/run-benchmark.yaml'
      params:
        <<: *run_stress_test_vars
      on_failure:
        put: slack-alert
        params:
          channel: '#((slack_channel_name))'
          attachments:
            - pretext: Survey Runner Stress Test Failed
              color: danger
              title: Concourse Build $BUILD_ID
              title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID
      on_success:
        put: slack-alert
        params:
          channel: '#((slack_channel_name))'
          attachments:
            - pretext: Survey Runner Stress Test Passed
              color: good
              title: Concourse Build $BUILD_ID
              title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID


##############################################################################
# Destroy Infrastructure
##############################################################################

  - name: destroy-infrastructure
    serial_groups: [run-stress-test]
    plan:
    - get: eq-terraform-load-generator
    - get: eq-infrastructure-build-image
      passed:
        - deploy-infrastructure
    - get: eq-survey-runner-benchmark
      passed:
        - run-stress-test
      trigger: true
    - task: Destroy Infrastructure
      file: 'eq-terraform-load-generator/ci/destroy-infrastructure.yaml'
      image: eq-infrastructure-build-image
      params:
        <<: *infrastructure_vars
    on_failure:
      put: slack-alert
      params:
        channel: '#((slack_channel_name))'
        attachments:
          - pretext: Load Generator Infrastructure Destroy Failed
            color: danger
            title: Concourse Build $BUILD_ID
            title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID
    on_success:
      put: slack-alert
      params:
        channel: '#((slack_channel_name))'
        attachments:
          - pretext: Load Generator Infrastructure Destroy Passed
            color: good
            title: Concourse Build $BUILD_ID
            title_link: $ATC_EXTERNAL_URL/builds/$BUILD_ID

